FROM node:14.15.1-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
COPY ./frontend ./
RUN npm install --silent
RUN npm install -g react-scripts --silent

CMD ["npm", "start"]